/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as CommitmentCallRouteImport } from './routes/commitmentCall'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as QuizQuestionIdRouteImport } from './routes/quiz/$questionId'

const IndexLazyRouteImport = createFileRoute('/')()

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitmentCallRoute = CommitmentCallRouteImport.update({
  id: '/commitmentCall',
  path: '/commitmentCall',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const QuizQuestionIdRoute = QuizQuestionIdRouteImport.update({
  id: '/quiz/$questionId',
  path: '/quiz/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/avatar': typeof AvatarRoute
  '/commitmentCall': typeof CommitmentCallRoute
  '/share': typeof ShareRoute
  '/quiz/$questionId': typeof QuizQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/avatar': typeof AvatarRoute
  '/commitmentCall': typeof CommitmentCallRoute
  '/share': typeof ShareRoute
  '/quiz/$questionId': typeof QuizQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/avatar': typeof AvatarRoute
  '/commitmentCall': typeof CommitmentCallRoute
  '/share': typeof ShareRoute
  '/quiz/$questionId': typeof QuizQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar'
    | '/commitmentCall'
    | '/share'
    | '/quiz/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/avatar' | '/commitmentCall' | '/share' | '/quiz/$questionId'
  id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/commitmentCall'
    | '/share'
    | '/quiz/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AvatarRoute: typeof AvatarRoute
  CommitmentCallRoute: typeof CommitmentCallRoute
  ShareRoute: typeof ShareRoute
  QuizQuestionIdRoute: typeof QuizQuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commitmentCall': {
      id: '/commitmentCall'
      path: '/commitmentCall'
      fullPath: '/commitmentCall'
      preLoaderRoute: typeof CommitmentCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$questionId': {
      id: '/quiz/$questionId'
      path: '/quiz/$questionId'
      fullPath: '/quiz/$questionId'
      preLoaderRoute: typeof QuizQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AvatarRoute: AvatarRoute,
  CommitmentCallRoute: CommitmentCallRoute,
  ShareRoute: ShareRoute,
  QuizQuestionIdRoute: QuizQuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
