/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WimmelbildRouteImport } from './routes/wimmelbild'
import { Route as ShareRouteImport } from './routes/share'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as QuizResultRouteImport } from './routes/quiz.result'
import { Route as QuizQuestionsRouteImport } from './routes/quiz.questions'
import { Route as QuizInformationRouteImport } from './routes/quiz.information'

const IndexLazyRouteImport = createFileRoute('/')()

const WimmelbildRoute = WimmelbildRouteImport.update({
  id: '/wimmelbild',
  path: '/wimmelbild',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const QuizResultRoute = QuizResultRouteImport.update({
  id: '/quiz/result',
  path: '/quiz/result',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuestionsRoute = QuizQuestionsRouteImport.update({
  id: '/quiz/questions',
  path: '/quiz/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizInformationRoute = QuizInformationRouteImport.update({
  id: '/quiz/information',
  path: '/quiz/information',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/avatar': typeof AvatarRoute
  '/engagement': typeof EngagementRoute
  '/share': typeof ShareRoute
  '/wimmelbild': typeof WimmelbildRoute
  '/quiz/information': typeof QuizInformationRoute
  '/quiz/questions': typeof QuizQuestionsRoute
  '/quiz/result': typeof QuizResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/avatar': typeof AvatarRoute
  '/engagement': typeof EngagementRoute
  '/share': typeof ShareRoute
  '/wimmelbild': typeof WimmelbildRoute
  '/quiz/information': typeof QuizInformationRoute
  '/quiz/questions': typeof QuizQuestionsRoute
  '/quiz/result': typeof QuizResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/avatar': typeof AvatarRoute
  '/engagement': typeof EngagementRoute
  '/share': typeof ShareRoute
  '/wimmelbild': typeof WimmelbildRoute
  '/quiz/information': typeof QuizInformationRoute
  '/quiz/questions': typeof QuizQuestionsRoute
  '/quiz/result': typeof QuizResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar'
    | '/engagement'
    | '/share'
    | '/wimmelbild'
    | '/quiz/information'
    | '/quiz/questions'
    | '/quiz/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar'
    | '/engagement'
    | '/share'
    | '/wimmelbild'
    | '/quiz/information'
    | '/quiz/questions'
    | '/quiz/result'
  id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/engagement'
    | '/share'
    | '/wimmelbild'
    | '/quiz/information'
    | '/quiz/questions'
    | '/quiz/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AvatarRoute: typeof AvatarRoute
  EngagementRoute: typeof EngagementRoute
  ShareRoute: typeof ShareRoute
  WimmelbildRoute: typeof WimmelbildRoute
  QuizInformationRoute: typeof QuizInformationRoute
  QuizQuestionsRoute: typeof QuizQuestionsRoute
  QuizResultRoute: typeof QuizResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wimmelbild': {
      id: '/wimmelbild'
      path: '/wimmelbild'
      fullPath: '/wimmelbild'
      preLoaderRoute: typeof WimmelbildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/result': {
      id: '/quiz/result'
      path: '/quiz/result'
      fullPath: '/quiz/result'
      preLoaderRoute: typeof QuizResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/questions': {
      id: '/quiz/questions'
      path: '/quiz/questions'
      fullPath: '/quiz/questions'
      preLoaderRoute: typeof QuizQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/information': {
      id: '/quiz/information'
      path: '/quiz/information'
      fullPath: '/quiz/information'
      preLoaderRoute: typeof QuizInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AvatarRoute: AvatarRoute,
  EngagementRoute: EngagementRoute,
  ShareRoute: ShareRoute,
  WimmelbildRoute: WimmelbildRoute,
  QuizInformationRoute: QuizInformationRoute,
  QuizQuestionsRoute: QuizQuestionsRoute,
  QuizResultRoute: QuizResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
