/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WimmelbildRouteImport } from './routes/wimmelbild'
import { Route as ShareRouteImport } from './routes/share'
import { Route as QuizResultRouteImport } from './routes/quiz-result'
import { Route as QuizQuestionsRouteImport } from './routes/quiz-questions'
import { Route as QuizInformationsRouteImport } from './routes/quiz-informations'
import { Route as CommitmentCallRouteImport } from './routes/commitment-call'
import { Route as AvatarRouteImport } from './routes/avatar'

const IndexLazyRouteImport = createFileRoute('/')()

const WimmelbildRoute = WimmelbildRouteImport.update({
  id: '/wimmelbild',
  path: '/wimmelbild',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizResultRoute = QuizResultRouteImport.update({
  id: '/quiz-result',
  path: '/quiz-result',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuestionsRoute = QuizQuestionsRouteImport.update({
  id: '/quiz-questions',
  path: '/quiz-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizInformationsRoute = QuizInformationsRouteImport.update({
  id: '/quiz-informations',
  path: '/quiz-informations',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitmentCallRoute = CommitmentCallRouteImport.update({
  id: '/commitment-call',
  path: '/commitment-call',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/avatar': typeof AvatarRoute
  '/commitment-call': typeof CommitmentCallRoute
  '/quiz-informations': typeof QuizInformationsRoute
  '/quiz-questions': typeof QuizQuestionsRoute
  '/quiz-result': typeof QuizResultRoute
  '/share': typeof ShareRoute
  '/wimmelbild': typeof WimmelbildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/avatar': typeof AvatarRoute
  '/commitment-call': typeof CommitmentCallRoute
  '/quiz-informations': typeof QuizInformationsRoute
  '/quiz-questions': typeof QuizQuestionsRoute
  '/quiz-result': typeof QuizResultRoute
  '/share': typeof ShareRoute
  '/wimmelbild': typeof WimmelbildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/avatar': typeof AvatarRoute
  '/commitment-call': typeof CommitmentCallRoute
  '/quiz-informations': typeof QuizInformationsRoute
  '/quiz-questions': typeof QuizQuestionsRoute
  '/quiz-result': typeof QuizResultRoute
  '/share': typeof ShareRoute
  '/wimmelbild': typeof WimmelbildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar'
    | '/commitment-call'
    | '/quiz-informations'
    | '/quiz-questions'
    | '/quiz-result'
    | '/share'
    | '/wimmelbild'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar'
    | '/commitment-call'
    | '/quiz-informations'
    | '/quiz-questions'
    | '/quiz-result'
    | '/share'
    | '/wimmelbild'
  id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/commitment-call'
    | '/quiz-informations'
    | '/quiz-questions'
    | '/quiz-result'
    | '/share'
    | '/wimmelbild'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AvatarRoute: typeof AvatarRoute
  CommitmentCallRoute: typeof CommitmentCallRoute
  QuizInformationsRoute: typeof QuizInformationsRoute
  QuizQuestionsRoute: typeof QuizQuestionsRoute
  QuizResultRoute: typeof QuizResultRoute
  ShareRoute: typeof ShareRoute
  WimmelbildRoute: typeof WimmelbildRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wimmelbild': {
      id: '/wimmelbild'
      path: '/wimmelbild'
      fullPath: '/wimmelbild'
      preLoaderRoute: typeof WimmelbildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-result': {
      id: '/quiz-result'
      path: '/quiz-result'
      fullPath: '/quiz-result'
      preLoaderRoute: typeof QuizResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-questions': {
      id: '/quiz-questions'
      path: '/quiz-questions'
      fullPath: '/quiz-questions'
      preLoaderRoute: typeof QuizQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-informations': {
      id: '/quiz-informations'
      path: '/quiz-informations'
      fullPath: '/quiz-informations'
      preLoaderRoute: typeof QuizInformationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commitment-call': {
      id: '/commitment-call'
      path: '/commitment-call'
      fullPath: '/commitment-call'
      preLoaderRoute: typeof CommitmentCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AvatarRoute: AvatarRoute,
  CommitmentCallRoute: CommitmentCallRoute,
  QuizInformationsRoute: QuizInformationsRoute,
  QuizQuestionsRoute: QuizQuestionsRoute,
  QuizResultRoute: QuizResultRoute,
  ShareRoute: ShareRoute,
  WimmelbildRoute: WimmelbildRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
